version: "3.8"
services:
  nginx:
    container_name: nginx
    depends_on:
      - frontend
      - backend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'
    networks:
      - portfolio
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.nginx
    container_name: frontend
    restart: on-failure
    # ports:
    #   - '3000:3000'
    networks:
      - portfolio
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure
    container_name: backend
    volumes:
      - public:/app/public
    # ports: 
    #   - '3001:3001'
    depends_on: 
      - mongodb
    networks:
      - portfolio
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    container_name: mongodb
    networks:
      - portfolio

volumes:
  data:
  public:

networks:
  portfolio: