version: "3.8"
services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    container_name: mongodb
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure
    container_name: backend
    volumes:
      - public:/app/public
    ports: 
      - '3001:3001'
    depends_on: 
      - mongodb
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.nginx
    container_name: frontend
    depends_on:
      - backend
    restart: on-failure
    ports:
      - '3000:3000'
  nginx:
    container_name: nginx
    depends_on:
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'


volumes:
  data:
  public: